reddit_lite/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :subs, except: [:destroy] do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:new, :create, :index]
end

reddit_lite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_lite/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  belongs_to :sub

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs

  has_many :subs,
    through: :post_subs,
    source: :sub

end

reddit_lite/app/models/post_sub.rb
class PostSub < ApplicationRecord

  belongs_to :post

  belongs_to :sub


end

reddit_lite/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subs

  has_many :posts,
    through: :post_subs,
    source: :post

  def ensure_moderator
    redirect_to subs_url unless @current_user == self.moderator
  end
end

reddit_lite/app/models/user.rb
class User < ApplicationRecord
  validates :password_digest, :username, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  attr_reader :password

  after_initialize :ensure_token

  has_many :subs,
    foreign_key: :moderator_id,
    class_name: :Sub

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.is_password?(password)
    nil
  end


end

reddit_lite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_token!
  end

  def logged_in?
    !!current_user
  end

  def logout!
    current_user.try(:reset_token)
    @current_user = nil
    session[:session_token] = nil
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

reddit_lite/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @subs = Sub.all
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.sub_id = params[:sub_id]
    if @post.save
      redirect_to sub_url(@post.sub_id)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to sub_url(@post.sub_id)
    end
  end

  def show
    @post = Post.find(params[:id])
    @sub = @post.sub
  end

  def edit
    @subs = Sub.all
    @post = Post.find(params[:id])
    redirect_to post_url(@post) unless current_user == @post.author
  end

  def update

    @post = Post.find(params[:id])
    redirect_to post_url(@post) unless current_user == @post.author
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])

  end

end

reddit_lite/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @user
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ['Invalid Credentials']
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

reddit_lite/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :ensure_moderator, only: [:edit, :update]

  def new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = Post.where(sub_id: params[:id]) + @sub.posts
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :moderator_id, :description)
  end


end

reddit_lite/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

reddit_lite/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_lite/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_lite/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit_lite/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_lite/app/helpers/users_helper.rb
module UsersHelper
end

reddit_lite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditLite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    Hey there, <%= current_user.username %>! Want to check out <a href="<%= subs_url %>">some subs?</a>
    <form class="" action="<%= session_url %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="submit" name="" value="Log Out">
    </form>
    <% end %>
    <%= yield %>
    <br>
    <div style ="color:red"><%= flash[:errors].join("<br>").html_safe if flash[:errors] %></div>
  </body>
</html>

reddit_lite/app/views/posts/edit.html.erb
<h1>Edit a Post</h1>

<form action="<%=post_url(@post)%>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label>Title:
    <input type="text" name="post[title]" value="<%=@post.title %>"></label>

  <label>URL:
    <input type="text" name="post[url]" value="<%=@post.url %>"></label>

  <label>Content:
    <input type="text" name="post[content]" value="<%=@post.content %>"></label>

  <input type="submit" name="" value="Edit post">

</form>

reddit_lite/app/views/posts/new.html.erb
<h1>Make a Post</h1>

<form action="<%=sub_posts_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label>Title:
    <input type="text" name="post[title]" value=""></label>

  <label>URL:
    <input type="text" name="post[url]" value=""></label>

  <label>Content:
    <input type="text" name="post[content]" value=""></label>

    <label>Cross post to:
      <ul>


    <% @subs.each do |sub| %>
    <li><%=sub.title%><input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"></li>
    <% end %>
    </ul>
      </label>

  <input type="submit" name="" value="Post your post">

</form>

reddit_lite/app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<h3>By: <%= @post.author.username %> </h3>
<p> <%= @post.content %> </p>
<br>
<a href= "<%= sub_url(@sub)%>" >Go to Subreddit</a>

reddit_lite/app/views/subs/edit.html.erb
<h1>Edit your Sub-Reddit!</h1>
<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">
  <label>
    Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  <label>
    Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>
    <input type="submit" name="" value="Edit Sub!">
</form>

reddit_lite/app/views/subs/index.html.erb
<h1>All The Subs</h1>
<form class="" action="<%= new_sub_url %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" name="" value="Create Sub-Reddit">
</form>
<ul>
  <% @subs.each do |sub| %>
    <li> <a href="<%= sub_url(sub) %>"> <%= sub.title %> </a>
    </li>
  <% end %>
</ul>

reddit_lite/app/views/subs/new.html.erb
<h1>Make a new Sub-Reddit!</h1>
<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Title
    <input type="text" name="sub[title]" value="">
  </label>
  <label>
    Description
    <input type="text" name="sub[description]" value="">
  </label>
    <input type="submit" name="" value="Create Sub!">
</form>

reddit_lite/app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>
<h3>Moderated By: <%= User.find(@sub.moderator_id).username %> </h3>
<h3>Description: <%= @sub.description %> </h3>

Posts go here (eventually):
<form class="" action="<%= new_sub_post_url(@sub) %>" method="get">
  <input type="submit" name="" value="Make a post!">
</form>

<ul>
<% @posts.each do |post| %>
  <li> <a href="<%=post_url(post)%>"> <%= post.title %></a>
    <% if post.author == current_user %>
      <form class="" action="<%= edit_post_url(post) %>" method="get">
        <input type="submit" name="" value="Edit post!">
      </form>
    <% end %>

  </li>
<% end %>
</ul>

reddit_lite/app/views/users/new.html.erb
<h1>Sign Up Here!</h1>
<form class="" action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>Password
    <input type="text" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Sign Up!">
</form>